cache:
  job:
    artifact_test: [ output_artifact.dat ]
    artifact_test_before_fixing: [ output_artifact.dat ]
    cache_test: [ output_job_cache.dat ]
    cache_test_with_ExpectHeader: [ output_job_cache.dat ]

shared:
    image: golang:1.19
    environment:
        GO111MODULE: on

jobs:
  TEST_HUB:
    requires: [ ]
    annotations:
      screwdriver.cd/virtualJob: true
    steps:
      - echo: echo "hello"

  artifact_test: &artifact-test
    environment: &artifact-env
      SD_DEBUG: "true"
      SD_ZIP_ARTIFACTS: "false"
      DD_CMD_SB: "10M"
      DD_CMD_COUNT: "10"
      OUTPUT_FILE_NAME: "output-artifact.dat"
    requires: [ ~TEST_HUB ]
    steps:
    - download-store-cli: &download-store-cli |
       go build -a -o store-cli
       ls -la store-cli
       chmod a+x store-cli
       ./store-cli -h
    - show-path-check-files: &show-path-check-files |
        echo $PATH
        ls -l ./
    - init-store-cli: &init-store-cli |
        mkdir -p ./tmp/sd
        OVERRIDE_PATH=$(readlink -f ./tmp/sd)
        STORE_CLI_PATH=$(which store-cli)

        cp -r /opt/sd/* ${OVERRIDE_PATH}/
        mv ./store-cli ${OVERRIDE_PATH}/

        export PATH=$(echo $PATH | sed -n "s%\/opt\/sd%${OVERRIDE_PATH}%p")
        which store-cli
    - create-artifacts: &create_outputfile |
       dd if=/dev/urandom of=${OUTPUT_FILE_NAME} bs=${DD_CMD_SB} count=${DD_CMD_COUNT}
       ls -lh ./${OUTPUT_FILE_NAME}
    - copy-artifact-dir: &copy-artifact-dir |
       echo $SD_ARTIFACTS_DIR
       cp ${OUTPUT_FILE_NAME} ${SD_ARTIFACTS_DIR}/${OUTPUT_FILE_NAME}
       echo "copy artifact dir"

  artifact_test_before_fixing:
    requires: [ ~TEST_HUB ]
    environment:
      <<: *artifact-env
      OUTPUT_FILE_NAME: "output_job_cache.dat"
    steps:
    - create-outputfile: *create_outputfile
    - copy-artifact-dir: *copy-artifact-dir

  cache_test:
    requires: [ ~TEST_HUB ]
    environment:
      <<: *artifact-env
      OUTPUT_FILE_NAME: "output_job_cache.dat"
    steps: &cache-step
    - download-store-cli: *download-store-cli
    - show-path-check-files: *show-path-check-files
    - init-store-cli: *init-store-cli
    - create-outputfile: *create_outputfile

  cache_test_with_ExpectHeader:
    requires: [ ~TEST_HUB ]
    environment:
      <<: *artifact-env
      OUTPUT_FILE_NAME: "output_job_cache.dat"
      SD_ENABLE_EXPECT_HEADER: "true"
    steps: *cache-step

  cache_test_with_ExpectHeader_and_long_timeout:
    requires: [ ~cache_test_with_ExpectHeader ]
    environment:
      <<: *artifact-env
      OUTPUT_FILE_NAME: "output_job_cache.dat"
      SD_ENABLE_EXPECT_HEADER: "true"
      CD_EXPECT_CONTINUE_TIMEOUT: 20
    steps: *cache-step
